# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='repeat_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
